### ISSUE TITLE
Does not work if the GitHub remote is not called origin

### ISSUE THREAD

**Issue by qc00** [github/vscode-github-actions#121]
**To Reproduce**
1. Clone GitHub repo and open in VS Code
2. Verify GitHub extensions work
3. `git remote rename origin fork`
4. Reload Window/restart app
5. Verify other GitHub extensions like PR still work
6. Actions extension displays: no GitHub repositories found

**Expected behavior**
The Actions extension continues to work (like the other extensions from GitHub) or provides an option to select a remote.

**Extension Version**
`v0.25.5`

**Comment by muzimuzhi** [comment]
typo in issue title: "if the GitHub **branch** is not called origin" -> "if the Git **remote** is not called origin"

**Comment by muzimuzhi** [comment]
Looks like for now you have to change config `github-actions.remote-name` per (vscode) project by hand.
![image](https://github.com/github/vscode-github-actions/assets/6376638/f485fdbd-f71a-470e-8645-50b6f702a212)

**Comment by qc00** [comment]
That worked. Thanks!

Ideally, this can be detected automatically like the other GitHub extensions

**Comment by muzimuzhi** [comment]
A list of remote names could be provided but user still need to make a choice if multiple remotes exist and several of them are cloned from github.

**Comment by muzimuzhi** [comment]
> A list of remote names could be provided but user still need to make a choice if multiple remotes exist and several of them are cloned from github.

I mean, in simple cases yes the remote could be automatically used, but in more general cases there might be multiple qualified remotes (typically an upstream and a fork).   In the latter case perhaps the extension could provide an easier way to switch between remotes.

**Comment by max-sixty** [comment]
I hit this in #96.

I'm surprised this requires manually configuration, particularly since often the correct remote will be `upstream` while the fork will be `origin`. Is my experience different from others'?

 The message is also very non-obvious (particularly since `origin` _was_ a GH repo, even if it wasn't one that runs GH Actions):

<img width="147" alt="image" src="https://github.com/github/vscode-github-actions/assets/5635139/835d3844-5e16-4829-9cc5-bbc73c8da24c">

Currently this is the only extension I need to configure for each project individually. A rule like "Try `origin`, if that doesn't work, try the other one" would catch most cases.

**Comment by KetchupOnMyKetchup** [comment]
The PR has been completed and the fix will be available in our upcoming release `v0.25.7`, which planned for release May 5, 2023. Thanks so much for submitting great bugs and feedback to help make the extension even better!

**Comment by KetchupOnMyKetchup** [comment]
The fix has been released and is available in `v0.25.7` 🎉 !
