### ISSUE TITLE
[Windows] Unable to find reusable workflow

### ISSUE THREAD

**Issue by dmmusil** [github/vscode-github-actions#174]
**Describe the bug**
This is the same as #68 but is still happening in the latest release of the extension on Windows 10.

**To Reproduce**
![image](https://github.com/github/vscode-github-actions/assets/4804276/b65be67b-eb63-49dd-ae1f-d9d5260f36e4)

**Expected behavior**
No warning about the workflow not being found.

**Screenshots**

**Extension Version**
`v0.25.6`

I tried downgrading and upgrading. No updates available for VS Code.

**Additional context**

**Comment by KetchupOnMyKetchup** [comment]
Hi @dmmusil,

I work on Windows 11 and am not able to repro the issue using the same file names you have in your example screenshot:
![reusableworkflowfix](https://github.com/github/vscode-github-actions/assets/7976517/214d309f-60d3-4fdc-b8ea-4acbff5cdc3a)

I also tried this on Windows 10:
![image](https://github.com/github/vscode-github-actions/assets/7976517/17681dba-075a-4962-8342-3d7bc257f019)

However, I did find an edge case bug where if you write the `uses` path first then create/name the file. For example:
1. Type `uses: ./.github/workflows/_build-and-test.yml` in `engage-main.yml`
2. Add a new file (or rename a file to be) called `_build-and-test.yml` and then the red error marks show up. 
3. If you are to reload the window at this point or close/reopen then the path will be fixed. But I agree that is an edge case bug.

Would you mind trying again with `v0.25.6` and reloading the window with Ctrl + Shift + P then Reload Window?
![image](https://github.com/github/vscode-github-actions/assets/7976517/5606a15a-482e-4192-8822-8d2ef96c42bd)

I think there is a chance you fell into the edge case I listed above, but if not would like to know more so that I can repro.

Thank you for your submission of the bug and for helping me repro this!!

**Comment by dmmusil** [comment]
Hi @KetchupOnMyKetchup, none of those help me, but one interesting thing I noticed is that this only happens in this one repository. If I open another where we reference shared workflows using the `./.github/...` pattern I don't see the false positive problems. Is there some cache somewhere that could be poisoned that I could clean up?

**Comment by KetchupOnMyKetchup** [comment]
@dmmusil HMM that's very interesting, I appreciate you finding that out and checking other repos. 

Is there any special about this repository that you can think of? What are the differences between this repo and the ones that worked? We had issues with multiple repos in one and a wiki repo breaking the extension for example. There could be something different about this one that is causing it.  

I'm unsure about the cache to cleanup part.

**Comment by dmmusil** [comment]
I will see if I can spin up the extension in development mode locally to try to get some more info about why it thinks these workflows don't exist.

**Comment by dmmusil** [comment]
Maybe that's not realistic given that the code is spread across multiple repositories. I don't immediately see what is different/special about this one repository. I tried to do a clean checkout and that didn't help either.

**Comment by dmmusil** [comment]
The issue persists in a fresh clone of the repository at a different path. So it's definitely something to do with the contents of this one repository.

**Comment by KetchupOnMyKetchup** [comment]
If you copy that folder with both the reusable workflow / one calling it to another repo, does it still happen? 

Are the worklflows calling other workflows across other repos?

Is it a very large repo?

**Comment by dmmusil** [comment]
If I copy one workflow that references one other workflow over to a repo where the false positive do not exist, everything works just like I'd expect.

**Comment by dmmusil** [comment]
Next experiment was to copy ALL the workflows from the bad repo into a good repo. They all work fine in the good repo. Let me know if there's any way for me to collect more data for you if that's of interest (debug logs, etc).

**Comment by KetchupOnMyKetchup** [comment]
I'd be curious if you pruned out everything in the bad repo except the workflows, if it was still broken. And if that works, then what chunk of that repo is breaking it. 

Is this the only issue you noticed that fails with the bad repo?

Is the good repo a NX workspace project also?

**Comment by dmmusil** [comment]
> I'd be curious if you pruned out everything in the bad repo except the workflows, if it was still broken. And if that works, then what chunk of that repo is breaking it.

I did try this and it was still broken in the bad repo.

> Is this the only issue you noticed that fails with the bad repo?

So far yes. This was happening in all repos and I've been working in this one for a while so I never realized there was a fix in the latest version until I went looking.

> Is the good repo a NX workspace project also?

No we just have a single NX repo

**Comment by dmmusil** [comment]
However, I shut down my computer last night and when I turned it on again this morning, everything is working correctly. So I wonder if there is some cache somewhere that wasn't letting go of the bad state. Thanks for helping me troubleshoot. Feel free to close this if you don't have any more questions.

**Comment by dmmusil** [comment]
I had tried lots of other "reboots" but not a full system reboot. I tried uninstalling the extension, downgrading and upgrading again, closing and reopening VS Code. I was about to try it on another Windows machine this morning but it worked when I booted it up to resume troubleshooting.

**Comment by KetchupOnMyKetchup** [comment]
Hmm that is super interesting, thank you for sharing with me what fixed it and everything you tried.  I will keep in mind that a full reboot can help and something might be getting cached in the future if others have issues with the extension. 

I really appreciate all your help in troubleshooting. Thank you so much ❤️ for keeping me in the loop and for working so hard to find out what the issue was so we could see if there was a bug that we should address!!!

**Comment by Maus3rSR** [comment]
I have exactly the same issue...

**Comment by douglasg14b** [comment]
Same issue here, feel like this has never worked, Running on WSL
