### ISSUE TITLE
Support syntax highlighting of `actions/github-script`

### ISSUE THREAD

**Issue by TaxBusby** [github/vscode-github-actions#194]
**Is your feature request related to a problem? Please describe.**
[`actions/github-script`](https://github.com/actions/github-script) is very helpful for writing clear logic in workflows, and I'm starting to use it more and more.

It is very convenient, it currently has no JS syntax highlighting for the code that I write.

**Describe the solution you'd like**
Automatically JS syntax-highlight `script:` inputs to `uses: actions/github-script` calls wherever they are found

The syntax highlighting should ideally include intellisense and other JS language features available in VSCode.

**Additional context**
[Opened discussion on actions/github-script](https://github.com/actions/github-script/discussions/385)

**Comment by felipesu19** [comment]
I think this is likely in the same place as having linting for bash scripts. We'd love to have it as a feature down the line, there are complexities involved in implementing and maintaining that make it more challenging than we can commit to right now.

**Comment by tdanecker** [comment]
I'd also really love to have syntax highlighting available for the javascript code itself via an embedded language (https://code.visualstudio.com/api/language-extensions/embedded-languages).

I think when the issue was moved to done, it was just for the highlighting of references in github expressions, but not for the javascript code itself?

It probably would make sense to reopen this issue instead of creating a new one for that feature request?

**Comment by dncrews** [comment]
@TaxBusby @tdanecker @felipesu19 @joshmgross FYI I [submitted a PR](https://github.com/github/vscode-github-actions/pull/571) to add this, and I also created [a plugin that does this](https://marketplace.visualstudio.com/items?itemName=dncrews.vscode-github-actions-embedded-syntax) with the same functionality to use in the mean time (or if they don't ever merge the PR).
