### ISSUE TITLE
Secrets are no longer secret.

### ISSUE THREAD

**Issue by jbkeg** [github/vscode-github-actions#324]
**Describe the bug**
I have a private repo in GitHub which I have no authority to access repository settings.
But I still can access to repository secrets and create/update/delete the secrets.

**To Reproduce**
Steps to reproduce the behaviour:
1. Link the repo which has no authority to access repo settings with vscode github actions extension.
2. At the extension can see/edit/create/delete the secrets.

**Expected behavior**
Supposed to be failed or blocked to read/write the secrets.

**Extension Version**
`v0.26.2`

**Comment by brignano** [comment]
I have observed the same behavior recently. This applies to secrets, variables, and environments.

**Comment by elbrenn** [comment]
The VSCode Extension uses our public [REST API](https://docs.github.com/en/rest/actions/secrets?apiVersion=2022-11-28#create-or-update-a-repository-secret)s to modify secrets and variables. Repo secrets and variables can be written written, modified and deleted with collaborator access to the repo

**Comment by brignano** [comment]
hi @elbrenn 👋🏻  

Sorry but, I'm having trouble following your response.

I understand you use the REST APIs to modify secrets and variables, I also do the same in some of my projects.

The problem is, if I create a personal access token for my user account- **I do not have permission to Get, Create, or Update, secrets in my organization**.

<img width="682" alt="image" src="https://github.com/github/vscode-github-actions/assets/9291621/2ead8bae-7ebe-4cfc-a5de-9a3c361c3a9f">

However, using this extension, I can bypass the organization restrictions and get, create, and update secrets which has created a huge security risk for us.

<img width="256" alt="image" src="https://github.com/github/vscode-github-actions/assets/9291621/ca920077-4561-465d-a5af-59ef355a5f32">

I'm really having trouble understanding how you are bypassing that authentication in this plug-in. I will keep going through the source code but I'm really surprised you aren't interested in entertaining the idea that this might be a problem.

**Comment by ews-ffarella** [comment]
Is this really fixed? It seesm to me that my isue #529 touches the same subject
