### ISSUE TITLE
Disable `secrets` validation in jobs when using dynamic `environment` 

### ISSUE THREAD

**Issue by SpencerKaiser** [github/vscode-github-actions#41]
**Describe the bug**
Referencing a secret that is stored at the environment level instead of a repository secret throws an warning

**To Reproduce**
1. Make a reference to a secret that is NOT at the repo level and is instead an environment secret
2. Observe warning inline and in the `Problems` tab

**Expected behavior**
Warnings will only be shown for secrets that are not found at the environment level OR the repo level

**Screenshots**
<img width="191" alt="image" src="https://user-images.githubusercontent.com/6445731/228051789-228baca9-dd11-480f-8b9c-994a21ae452e.png">
<img width="217" alt="image" src="https://user-images.githubusercontent.com/6445731/228052057-f1be1dbf-8669-4409-b017-b77219275879.png">
<img width="366" alt="image" src="https://user-images.githubusercontent.com/6445731/228051992-a1557a05-d4ef-4fd8-ad76-241b2d86e8ad.png">

**Extension Version**
`v0.25.2`

**Comment by cschleiden** [comment]
@SpencerKaiser are you able to share more of the workflow? Are those variables defined at the job or step level? Does the job contain `environment: prod` or is it using a dynamic expression to determine the environment to use?

**Comment by cschleiden** [comment]
@SpencerKaiser no that helps, thanks for the details! 

Yes, so we detect what environment is being used in a job, and only then add the environment secrets to the `secrets` context for that job. 

Obviously this doesn't work when `environment:` uses a dynamic expression that we cannot evaluate at edit time. The fix for now would be to disable `secrets` validation for such a job. 

I've updated the issue title to reflect this a bit better.

**Comment by KetchupOnMyKetchup** [comment]
The fix has been released and is available in `v0.25.7` 🎉 !
