### ISSUE TITLE
File can't be formatted while it's detected as GitHub Actions Workflow

### ISSUE THREAD

**Issue by krokofant** [github/vscode-github-actions#43]
**Describe the bug**
The file cannot be formatted while it's detected as a GitHub Actions Workflow.

**To Reproduce**
Install the Prettier extension: esbenp.prettier-vscode
Use these settings:
```
"**/.github/**/*.yml": "github-actions-workflow",
"[yaml]": {
  "editor.defaultFormatter": "esbenp.prettier-vscode"
},
"[github-actions-workflow]": {
  "editor.defaultFormatter": "esbenp.prettier-vscode",
},
```
Try to format the file, it doesn't work.

**Expected behavior**
The file should be able to be formatted.

**Screenshots**

**Extension Version**
`v0.25.6`

**Additional context**

**Comment by worgarside** [comment]
@krokofant what was your solution to this?

**Comment by krokofant** [comment]
> @krokofant what was your solution to this?

I restarted VS Code after the extension update and it started to work 😆

**Comment by JelsB** [comment]
For anyone else that ended up here trying to use the default formatter `"editor.defaultFormatter":  "redhat.vscode-yaml",`, that one just does not work. It worked flawlessly when I used `"editor.defaultFormatter": "esbenp.prettier-vscode"` (after installing the Prettier extension). It must be an issue with `redhat.vscode-yaml"` because there is a [similar problem with ansible files](https://github.com/redhat-developer/vscode-yaml/issues/812)

**Comment by krokofant** [comment]
I'm running VS Code Insiders. Now despite restarting or setting prettier as the default formatter globally or for just github-actions-workflow it doesn't work. Right-clicking doesn't display a formatting action either.
